language: php
php:
  - '7.2'
  - '7.3'

addons:
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

before_script:
- composer install
- composer require zendframework/zend-i18n zendframework/zend-db

script:
- sonar-scanner || travis_terminate 1;
- composer cs-check || travis_terminate 1;
- composer phpmd || travis_terminate 1;
- ./vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml || travis_terminate 1;

after_script:
- ./vendor/bin/coveralls -v
- ./vendor/bin/test-reporter -v --coverage-report=./test/logs/clover.xml
